// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYyAnRLrhkh0ti8126uEBUN_EPXubJ75Y',
    appId: '1:911481018045:web:39451cdadadd84abf489d4',
    messagingSenderId: '911481018045',
    projectId: 'video-uploading-app-56',
    authDomain: 'video-uploading-app-56.firebaseapp.com',
    storageBucket: 'video-uploading-app-56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzzs0HHVMkFMC72FRvAa-r8liTqO0SnIE',
    appId: '1:911481018045:android:c4e06e1b62382535f489d4',
    messagingSenderId: '911481018045',
    projectId: 'video-uploading-app-56',
    storageBucket: 'video-uploading-app-56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfMcnxdc2WbfTcshYNhT0ET-A8pVaBxHQ',
    appId: '1:911481018045:ios:d152eeab0f94ce1df489d4',
    messagingSenderId: '911481018045',
    projectId: 'video-uploading-app-56',
    storageBucket: 'video-uploading-app-56.appspot.com',
    iosBundleId: 'com.example.internAssignmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfMcnxdc2WbfTcshYNhT0ET-A8pVaBxHQ',
    appId: '1:911481018045:ios:32bddf7e6f610dfdf489d4',
    messagingSenderId: '911481018045',
    projectId: 'video-uploading-app-56',
    storageBucket: 'video-uploading-app-56.appspot.com',
    iosBundleId: 'com.example.internAssignmentApp.RunnerTests',
  );
}
